### ISSUE TITLE
Extractor Support? unapply method support

### ISSUE THREAD

**Issue by Qiyamah** [JuliaServices/Match.jl#44]
Hi,

Is there a support for unapply method like in Scala Extractors? If so, can you share an example?

Thanks

**Comment by Qiyamah** [comment]
```Julia
macroexpand(:(@match def begin
                  Def(d::Vector) => "found it"
                  _ => "nothing"
              end))
quote  # REPL[17], line 2:
    if (def isa Def && length(fieldnames(Def)) == 1) && getfield(def, 1) isa Vector # /home/rra/.julia/v0.6/Match/src/matchmacro.jl, line 389:
        "found it"
    else  # /home/rra/.julia/v0.6/Match/src/matchmacro.jl, line 391:
        begin  # REPL[17], line 3:
            "nothing"
        end
    end
end

```

I think the expansion should be something like:

```Julia
if (def isa Def && length(fieldnames(def)) == 1) && getfield(def, 1) isa Vector
```

**Comment by kmsquire** [comment]
Not at a computer right now, so I can’t test this, but I’m pretty sure it’s fine as is. In Julia, concrete types can’t be subclassed, and abstract types don’t have fields. So `fieldnames(Def)` and `fieldnames(def)` should always be equivalent if `def ` is a `Def`. 

I’m assuming you kind of answered your first question yourself, but the short answer is that there is no support for an `unapply` method, and the match macro simply assumes it can match and assign values by position. This can easily be an incorrect assumption. 

If you’re up to digging through the code and adding such support, please let me know! I suspect it would be a little challenging, but the attempt would be welcome. Cheers!


do look through the docs for further examples.

**Comment by gafter** [comment]
The expansion is completely different in version 2 of the package, but I believe it has the same correct semantics.  The expansion may be ugly but it generates fast, compact code.

If you're making a feature request, please open a new issue.
