### ISSUE TITLE
Confusion between symbols and variables

### ISSUE THREAD

**Issue by jamii** [JuliaServices/Match.jl#45]
``` julia
julia> x = 42
42

julia> @match(:x, :x)
42
```

**Comment by MasonProtter** [comment]
Is this fixed now?
```julia
julia> x = 42
42

julia> @match(:x, :x)
true
```

**Comment by gafter** [comment]
In version 2, we no longer support this undocumented version of the `@match` macro.  But I think things work as expected.  Note that when you use `x` in a pattern, it binds the matching input value to the value of a variable named `x` locally, which may be different from the `x` on the outside.

```julia-repl
julia> using Match

julia> Pkg.status()
      Status `~/.julia/environments/v1.6/Project.toml`
  [7eb4fadd] Match v2.0.0

julia> x = 42
42

julia> @match x begin
           x => "yes: $x"
       end
"yes: 42"

julia> @match (:x, :x) begin
           (x, :x) => "yes: $x"
       end
"yes: x"

julia> @match (x, :x) begin
           (x, :x) => "yes: $x"
       end
"yes: 42"
```

Please open a new bug if this explanation is not satisfactory.
