### ISSUE TITLE
Wrong result for enum

### ISSUE THREAD

**Issue by bliang26** [JuliaServices/Match.jl#56]
Hi, I am getting a wrong result when I try to match an enum.  Please see the following example. Is there any work around? Thanks.

```julia
julia> @enum Fruit begin
       orange
       apple
       end

julia> fruit = orange
orange::Fruit = 0

julia> @match fruit begin
       apple  => "apple"
       orange => "orange"
       end
"apple"

```

**Comment by thautwarm** [comment]
@bliang26 
In `apple => "apple"`, the first `apple` is treated as a symbol to capture.

According to the Match.jl's documents, now you cannot reference variables to compare with the value to match.

And in MLStyle.jl, use `&`:

```julia
julia> using MLStyle

julia> @enum Fruit begin
              orange
              apple
              end
julia> fruit = orange
orange::Fruit = 0

julia> @match fruit begin
              &apple  => "apple"
              &orange => "orange"
       end
"orange"
```

What you want is the pin operators from Elixir language.

**Comment by norru** [comment]
```
match C begin
           &A => "A"
           &B => "B"
           &C => "C"
       end
ERROR: syntax: invalid syntax &A
```

**Comment by norru** [comment]
Just had this problem, caused a bug which lost me hours to track down as I was incorrectly assuming this module would work as it would have in other languages.

As this is my most common use case, I won't be able to continue using this package.

**Comment by thautwarm** [comment]
@norru so try MLStyle.jl? :-)

**Comment by gafter** [comment]
```julia-repl
julia> Pkg.status()
      Status `~/.julia/environments/v1.6/Project.toml`
  [7eb4fadd] Match v2.0.0

julia> @enum Fruit begin
              orange
              apple
              end

julia> fruit = orange
orange::Fruit = 0

julia> @match fruit begin
              $apple  => "apple"
              $orange => "orange"
              end
"orange"
```
