### ISSUE TITLE
The pattern `nothing` matches any expressions

### ISSUE THREAD

**Issue by lihebi** [JuliaServices/Match.jl#60]
The pattern `nothing` seems to successfully match any expressions:

```julia
@match 1 begin
    nothing => true
    _ => false
end
# => true
```

```julia
@match "hello" begin
    nothing => true
    _ => false
end
# => true
```

**Comment by caseykneale** [comment]
Someone in the Julia discord found a similar bug that has a similar `smell` too it.
```
g = @match Symbol begin
    String => 1
    Symbol => 2
    _ => 3
end
```
will give `g == 1`.
Infact, you can change the type of the first match condition to anything and I believe it will always select the first condition for it's result.

Not sure what's going on in this case, the quick fix I suggested to them was to convert types to symbols and match or if/then on those.

**Comment by gafter** [comment]
An identifier as a pattern matches any input and binds the input to a variable of that name.  `nothing` and `String` are just names that can be bound.

If you want to test for the value `nothing`, use the pattern `$nothing`.

If you want to test for the type `String`, use the pattern `::String`.
