### ISSUE TITLE
Doesn't seem to support matching variables like Scala, is that intentional?

### ISSUE THREAD

**Issue by lotcher** [JuliaServices/Match.jl#72]
In Scala, we can match as follows
```scala
scala> val a = 1
scala> 2 match {
      case a => 1
      case 2 => 2
  }
>>> 2
```
But does Match only support literal matching? Or is it the bad way I use it
```julia
julia> @match 2 begin
           a => 1
           2 => 2
           end
>>>1
```
What should I do when I want to match a variable on the type? Thank you for your help

**Comment by gafter** [comment]
`a` is a pattern that matches anything and binds it to a variable named `a`.  `@match` doesn't support general expressions, but when we integrate `Rematch2.jl` to be the newest version of this package, you will be able to write this:

```julia
julia> const a = 1
1

julia> @match 2 begin
         $a => 1
         2 => 2
       end
2
```
