### ISSUE TITLE
Open to transferring ownership/maintenance of package?

### ISSUE THREAD

**Issue by quinnj** [JuliaServices/Match.jl#74]
Hey @kmsquire, @gafter has been working on a fancy new implementation of pattern-matching over [here](https://github.com/gafter/Rematch2.jl) and it's been fun to see the functionality and performance we're able to achieve.

We started discussing the best way to publish his code and we identified Match.jl as the ideal name/home. Would you be open to transferring the repo to the JuliaServices GitHub org? (we use it as a sort of "general utility" kind of org for application support). We'd like to take over maintenance of the package and do a 2.0 release. @gafter's new macro is mostly a superset of everything Match.jl currently supports, w/ a [few differences](https://github.com/gafter/Rematch2.jl#rematch-differs-from-match-in-the-following-ways). We've also started identifying public packages that directly depend on Match.jl and how we could help them upgrade and if there would be any unexpected changes (and mitigate in the mean time!).

Anyway, would love to hear your opinion/thoughts; we noticed the package hasn't had a lot of updates/changes over the last several years, so thought it was worth asking if we could take it over to keep pushing pattern matching functionality forward in Julia. Cheers!

**Comment by NHDaly** [comment]
Linking in a previous discussion:
https://github.com/RelationalAI-oss/Rematch.jl/issues/25

**Comment by quinnj** [comment]
Bump @kmsquire?

**Comment by quinnj** [comment]
Transferred! Thanks @kmsquire!
