### ISSUE TITLE
a new pattern match for Julia

### ISSUE THREAD

**Issue by Roger-luo** [JuliaServices/Match.jl#77]
Hi @gafter 

@NHDaly told me about your work on JuliaCon, I was working on some sum types and pattern match in Expronicon.jl and was thinking to refactor MLStyle.jl, we have a group of people want pattern match from JuliaCon, maybe we should find a time to discuss our use cases and ideas.

cc: @c42f

**Comment by gafter** [comment]
Would love to discuss, perhaps by video?  You are welcome to contact me (or propose a calendar event) at neal.gafter@relational.ai .

**Comment by NHDaly** [comment]
Did this ever get addressed? You might want to share your personal contact info here for after you retire (and lose your RAI email)?

**Comment by gafter** [comment]
My email address has been updated in https://github.com/JuliaServices/Match.jl/commit/4988ecc74ef72480a2523cf45ad9ed78410e7b18
