### ISSUE TITLE
Support ML-style active patterns

### ISSUE THREAD

**Issue by gafter** [JuliaServices/Match.jl#92]
See the documentation about "active patterns" in [MLStyle](https://thautwarm.github.io/MLStyle.jl/latest/syntax/pattern.html#active-patterns) and [F#](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/active-patterns).  We should consider supporting those.

**Comment by nystrom** [comment]
The old `Rematch` had a PR for Scala-like extractors, which are similar.
https://github.com/RelationalAI-oss/Rematch.jl/pull/28
