### ISSUE TITLE
Possible to match a NamedTuple?

### ISSUE THREAD

**Issue by fredcallaway** [JuliaServices/Match.jl#95]
I didn't see this in the docs so I assume it's not possible. It would be really nice to be able to match NamedTuples, e.g.

```julia
@match (;a=1, b=2) begin
    (;a=1, b) => begin
        # I would like to have locals a = 1 and b = 2
    end
end
```

**Comment by xukai92** [comment]
had a similar need and found the following work-around works
```julia
nt = (; a=1, b=2)
NT = typeof(nt)
@match (; a, b) = nt begin
    NT(1, b) => begin
        # you have access to locals a = 1 and b = 2 here
    end
end
```

**Comment by fredcallaway** [comment]
@xukai92 It looks like this only works for a single type of named tuple. Could be handy, but definitely not a complete solution.
